spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:${PORT}/${DB}
    username: ${USERNAME}
    password: ${PASSWORD}
  flyway:
    baseline-on-migrate: true
    baseline-description: "data_insertion"
    enabled: true
    user: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://${HOST}:${PORT}/${DB}
springfox:
  documentation:
    swagger-ui:
      enabled=true: